branch-defaults:
  main:
    environment: js-env
    group_suffix: null
#deploy:
#  artifact: /Users/rasulkadraliev/Python/jobSearch.zip
environment-defaults:
  jobSearch-env:
    branch: null
    repository: null
global:
  application_name: js
  branch: null
  default_ec2_keyname: aws-js
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
